ALTER TABLE APP_ACT_KMS_CARD ADD ISRATE SMALLINT default NULL;
ALTER TABLE APP_ACT_KMS_FILE ALTER COLUMN FILENAME SET DATA TYPE NVARCHAR(256);
CALL SYSPROC.ADMIN_CMD('REORG TABLE APP_ACT_KMS_CARD');
UPDATE APP_ACT_KMS_CARD SET ISRATE = 1;